---
- include: get-dlrn-hash.yml
  when: dlrn_hash_tag is defined and dlrn_task_run is not defined

- include: get-dlrn-hash-newest.yml
  when: dlrn_hash_tag_newest is defined and dlrn_task_run_newest is not defined

- name: Create repo setup script
  template:
    src: "{{ repo_setup_script_source }}"
    dest: "{{ repo_setup_dir }}/{{ repo_setup_script }}"
    mode: 0755

- include: setup_repos.yml
  static: no
  when: repo_run_live|bool

- include: inject_repos_into_image.yml
  static: no
  when: repo_inject_image_path is defined
